name: Build GDExtension
on:
  workflow_call:
  push:

env:
  LIBNAME: example

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:

          - platform: linux
            float-precision: double
            arch: x86_64
            os: ubuntu-20.04
          - platform: windows
            float-precision: double
            arch: x86_32
            os: windows-latest
          - platform: windows
            float-precision: double
            arch: x86_64
            os: windows-latest
          - platform: android
            float-precision: double
            arch: arm64
            os: ubuntu-20.04
          - platform: android
            float-precision: double
            arch: arm32
            os: ubuntu-20.04
          - platform: android
            float-precision: double
            arch: x86_64
            os: ubuntu-20.04
          - platform: android
            float-precision: double
            arch: x86_32
            os: ubuntu-20.04
          - platform: web
            float-precision: double
            arch: wasm32
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
# Lint
      #- name: Setup clang-format
      #  shell: bash
      #  run: |
      #    python -m pip install clang-format
      #- name: Run clang-format
      #  shell: bash
      #  run: |
      #    clang-format src/** --dry-run --Werror
# Build
      - name: 🔗 GDExtension Build
        uses: ./.github/actions/build
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          godot-cpp-location: godot-cpp
          float-precision: ${{ matrix.float-precision }}
          build-target-type: template_release
# Sign
      - name: Mac Sign
        if: ${{ matrix.platform == 'macos' }}
        uses: ./.github/actions/sign
        with:
          FRAMEWORK_PATH: bin/macos/macos.framework
          APPLE_CERT_BASE64: ${{ secrets.APPLE_CERT_BASE64 }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_DEV_PASSWORD: ${{ secrets.APPLE_DEV_PASSWORD }}
          APPLE_DEV_ID: ${{ secrets.APPLE_DEV_ID }}
          APPLE_DEV_TEAM_ID: ${{ secrets.APPLE_DEV_TEAM_ID }}
          APPLE_DEV_APP_ID: ${{ secrets.APPLE_DEV_APP_ID }}

      - name: Windows - Delete compilation files
        if: ${{ matrix.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item demo/addons/gameplay_effects/bin/windows/* -Include *.exp,*.lib,*.pdb -Force
      - name: Upload Artifact
        uses: actions/upload-artifact/merge@v4
        with:
          name: godot-cpp-template
          path: |
            ${{ github.workspace }}/demo/addons/**
